import type { ElementType } from 'react';
import {
  Zap,
  Clock,
  Printer,
  ShieldCheck,
  Wrench,
  Utensils,
  Package,
  AlertTriangle,
  Truck,
  RefreshCw,
  Boxes,
  FileText,
  ShoppingBag,
  Tag,
  RotateCcw,
  MessageSquare,
  Palette,
  TrendingUp,
  Calendar,
  Users,
  BookOpen,
  Award,
  CreditCard,
  BarChart3,
  UserCheck,
  Sparkles,
  Settings,
  Store,
} from 'lucide-react';

export type ToolCategory = 'pos' | 'inventory' | 'sales' | 'customers' | 'finance';

export interface ToolItem {
  id: string;
  title: string;
  description: string;
  href: string;
  icon: ElementType;
  badge?: string;
  badgeType?: 'success' | 'warning' | 'info' | 'purple';
  category: ToolCategory;
}

export const OPERATION_MODES = [
  {
    id: 'retail',
    title: 'Retail Mode',
    subtitle: 'Fast Barcode & Cashier',
    icon: Store,
    href: '/pos?mode=retail',
    border: 'border-emerald-500/30',
    bgGradient: 'from-emerald-500/20 to-teal-500/10',
    textGlow: 'text-emerald-400',
    badge: 'Fast 3s Ring-Up',
  },
  {
    id: 'restaurant',
    title: 'Restaurant & KOT',
    subtitle: 'Table Map & Kitchen Orders',
    icon: Utensils,
    href: '/restaurant',
    border: 'border-amber-500/30',
    bgGradient: 'from-amber-500/20 to-orange-500/10',
    textGlow: 'text-amber-400',
    badge: 'Table Management',
  },
  {
    id: 'repair',
    title: 'Repair & Job Sheet',
    subtitle: 'Job Cards & Intake Slips',
    icon: Wrench,
    href: '/repairs',
    border: 'border-blue-500/30',
    bgGradient: 'from-blue-500/20 to-indigo-500/10',
    textGlow: 'text-blue-400',
    badge: 'Job Sheet Generator',
  },
  {
    id: 'hire_purchase',
    title: 'Hire Purchase',
    subtitle: 'Installment Contracts & NIC',
    icon: CreditCard,
    href: '/hire-purchase',
    border: 'border-emerald-500/30',
    bgGradient: 'from-emerald-500/20 to-cyan-500/10',
    textGlow: 'text-emerald-400',
    badge: 'Micro-Credit',
  },
  {
    id: 'quotations',
    title: 'B2B Quotations',
    subtitle: 'Wholesale & Proforma Bills',
    icon: FileText,
    href: '/quotations',
    border: 'border-purple-500/30',
    bgGradient: 'from-purple-500/20 to-pink-500/10',
    textGlow: 'text-purple-400',
    badge: 'Proforma Suite',
  },
  {
    id: 'appointments',
    title: 'Appointments',
    subtitle: 'Client Slots & Specialists',
    icon: Calendar,
    href: '/appointments',
    border: 'border-cyan-500/30',
    bgGradient: 'from-cyan-500/20 to-blue-500/10',
    textGlow: 'text-cyan-400',
    badge: 'Booking Hub',
  },
] as const;

export const ALL_MERCHANT_TOOLS: ToolItem[] = [
  {
    id: 'pos_retail',
    title: 'Retail POS Counter',
    description: 'Sub-3s cashier checkout, barcode scanning, cash tender & hotkeys',
    href: '/pos',
    icon: Zap,
    badge: 'PRIMARY POS',
    badgeType: 'success',
    category: 'pos',
  },
  {
    id: 'pos_shifts',
    title: 'Register Shift & Z-Report',
    description: 'Open/close shift cash drawer float, record cash drops & end-of-day balances',
    href: '/shifts',
    icon: Clock,
    category: 'pos',
  },
  {
    id: 'pos_barcodes',
    title: 'Barcode Sticker Studio',
    description: '50×25mm shelf tags, jewelry stickers & thermal label printer studio',
    href: '/barcodes',
    icon: Printer,
    badge: '50x25mm STD',
    badgeType: 'success',
    category: 'pos',
  },
  {
    id: 'pos_approval',
    title: 'Manager Approval Guard',
    description: 'Server-validated RBAC manager overrides for high discounts & voids',
    href: '/pos',
    icon: ShieldCheck,
    badge: 'RBAC Active',
    badgeType: 'purple',
    category: 'pos',
  },
  {
    id: 'pos_repairs',
    title: 'Phone & Electronics Repairs',
    description: 'Job card intake, parts estimation, technician commission & claim slips',
    href: '/repairs',
    icon: Wrench,
    badge: 'JOB CARDS',
    badgeType: 'info',
    category: 'pos',
  },
  {
    id: 'pos_restaurant',
    title: 'Restaurant Tables & KOT',
    description: 'Interactive floor map, table dining orders, chef KOT printing & settlements',
    href: '/restaurant',
    icon: Utensils,
    badge: 'KOT SYSTEM',
    badgeType: 'warning',
    category: 'pos',
  },
  {
    id: 'inv_products',
    title: 'Product Catalogue & SKUs',
    description: 'Manage items, variant matrix, prices, cost & supplier details',
    href: '/products',
    icon: Package,
    category: 'inventory',
  },
  {
    id: 'inv_damages',
    title: 'Damages & Stock Write-Off',
    description: 'Audit broken, expired or spoiled inventory and reconcile stock',
    href: '/damages',
    icon: AlertTriangle,
    badge: 'LOSS AUDIT',
    badgeType: 'warning',
    category: 'inventory',
  },
  {
    id: 'inv_suppliers',
    title: 'Supplier & Vendor Directory',
    description: 'Manage suppliers, contact directories & purchase history',
    href: '/suppliers',
    icon: Truck,
    category: 'inventory',
  },
  {
    id: 'inv_transfers',
    title: 'Inter-Branch Transfers',
    description: 'Transfer stock between branches with in-transit locking & receipt',
    href: '/inventory',
    icon: RefreshCw,
    category: 'inventory',
  },
  {
    id: 'inv_grn',
    title: 'Goods Received Vouchers (GRN)',
    description: 'Receive bulk stock shipments from suppliers and update cost base',
    href: '/purchasing',
    icon: Boxes,
    category: 'inventory',
  },
  {
    id: 'inv_warranties',
    title: 'Serial & Warranty Registry',
    description: 'IMEI & serial number search, warranty certificate logs & claims',
    href: '/warranties',
    icon: ShieldCheck,
    category: 'inventory',
  },
  {
    id: 'sales_quotations',
    title: 'B2B Quotations & Invoicing',
    description: 'Generate corporate price quotes, proforma estimates & convert to sales',
    href: '/quotations',
    icon: FileText,
    badge: 'B2B SUITE',
    badgeType: 'purple',
    category: 'sales',
  },
  {
    id: 'sales_orders',
    title: 'Order Management Dashboard',
    description: 'View, fulfill & track orders from storefront, WhatsApp, and phone channels',
    href: '/orders',
    icon: ShoppingBag,
    badge: 'LIVE',
    badgeType: 'success',
    category: 'sales',
  },
  {
    id: 'sales_discounts',
    title: 'Discounts & Promo Engine',
    description: 'Create percentage or fixed-amount coupon codes for online & in-store',
    href: '/discounts',
    icon: Tag,
    badge: 'PROMO',
    badgeType: 'success',
    category: 'sales',
  },
  {
    id: 'sales_returns',
    title: 'Returns & Refunds',
    description: 'Process customer returns, select disposition, and issue refunds',
    href: '/returns',
    icon: RotateCcw,
    category: 'sales',
  },
  {
    id: 'sales_whatsapp',
    title: 'WhatsApp Automation Center',
    description: 'Cloud API bot & broadcasts — also in Social Channel Manager',
    href: '/social?tab=whatsapp',
    icon: MessageSquare,
    badge: 'AI Active',
    badgeType: 'success',
    category: 'sales',
  },
  {
    id: 'sales_social',
    title: 'Social Channel Manager',
    description: 'Facebook, Instagram, TikTok, WhatsApp handles — pixels, creative ads, catalog feeds',
    href: '/social',
    icon: TrendingUp,
    badge: 'HUB',
    badgeType: 'purple',
    category: 'sales',
  },
  {
    id: 'sales_creative',
    title: 'Creative Factory Studio',
    description: 'PDF, video & UGC ads — opens from Social Hub or direct studio tools',
    href: '/creative/dashboard',
    icon: Sparkles,
    badge: 'R6',
    badgeType: 'purple',
    category: 'sales',
  },
  {
    id: 'sales_automation',
    title: 'Automation Rules',
    description: 'ORDER_CREATED triggers, WhatsApp actions, and audit logs',
    href: '/settings/automation',
    icon: Sparkles,
    badge: 'EVENTS',
    badgeType: 'info',
    category: 'sales',
  },
  {
    id: 'sales_approvals',
    title: 'Approval Center',
    description: 'Review Jarvis high-risk actions before execution',
    href: '/approvals',
    icon: ShieldCheck,
    badge: 'EXECUTE',
    badgeType: 'warning',
    category: 'finance',
  },
  {
    id: 'sales_agents',
    title: 'Agent Orchestrator',
    description: '12 DB-grounded agents: core commerce + all vertical modules',
    href: '/ai/agents',
    icon: Sparkles,
    badge: 'R6',
    badgeType: 'purple',
    category: 'finance',
  },
  {
    id: 'sales_builder',
    title: 'Visual Storefront Builder',
    description: 'Customize shop design tokens, themes, and banner sections',
    href: '/store/builder',
    icon: Palette,
    badge: '6 FREE Themes',
    badgeType: 'purple',
    category: 'sales',
  },
  {
    id: 'cust_appointments',
    title: 'Appointments & Booking',
    description: 'Schedule service bookings, client time slots & specialist allocations',
    href: '/appointments',
    icon: Calendar,
    badge: 'BOOKINGS',
    badgeType: 'info',
    category: 'customers',
  },
  {
    id: 'cust_directory',
    title: 'Customer 360 & Directory',
    description: 'Omnichannel purchase history, lifetime spend & preferred channels',
    href: '/customers',
    icon: Users,
    category: 'customers',
  },
  {
    id: 'cust_polim_potha',
    title: 'Polim Potha Debt Ledger',
    description: 'Sri Lankan credit ledger for pay-later sales & WA reminder CTA',
    href: '/polim-potha',
    icon: BookOpen,
    category: 'customers',
  },
  {
    id: 'cust_loyalty',
    title: 'Polim Points Loyalty',
    description: 'Omnichannel customer points earning & redemption rules',
    href: '/loyalty',
    icon: Award,
    category: 'customers',
  },
  {
    id: 'fin_hire_purchase',
    title: 'Hire Purchase & Installments',
    description: 'Issue installment contracts, calculate repayments & track guarantors',
    href: '/hire-purchase',
    icon: CreditCard,
    badge: 'MICRO-CREDIT',
    badgeType: 'success',
    category: 'finance',
  },
  {
    id: 'fin_reports',
    title: 'Reports & Analytics',
    description: 'Revenue dashboards, profit margins, top sellers & CSV export',
    href: '/reports',
    icon: BarChart3,
    badge: 'LIVE DATA',
    badgeType: 'success',
    category: 'finance',
  },
  {
    id: 'fin_staff',
    title: 'Staff & Team Permissions',
    description: 'Invite team members and manage cashier/manager/owner roles',
    href: '/settings/staff',
    icon: UserCheck,
    category: 'finance',
  },
  {
    id: 'fin_jarvis',
    title: 'Jarvis AI Demand Predictor',
    description: 'Velocity-based stockout forecasts, sales analytics & Auto PO hints',
    href: '/ai/demand',
    icon: Sparkles,
    badge: 'Predictor Active',
    badgeType: 'purple',
    category: 'finance',
  },
  {
    id: 'fin_settings',
    title: 'Store Settings & Tax',
    description: 'Company details, receipt logo, VAT/SVAT configurations & currency setup',
    href: '/settings',
    icon: Settings,
    category: 'finance',
  },
];

export const CATEGORY_TABS: Array<{ id: string; label: string }> = [
  { id: 'all', label: 'All Modules' },
  { id: 'pos', label: 'Point of Sale' },
  { id: 'inventory', label: 'Inventory & Stock' },
  { id: 'sales', label: 'Omnichannel Sales' },
  { id: 'customers', label: 'Customers & Debt' },
  { id: 'finance', label: 'Finance & Admin' },
];
