import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { eq, inArray, and } from 'drizzle-orm';
import { db, products, businessProfile } from '@/db';
import type { BrandBrain } from '@/lib/creative/brand-brain';

export type PdfTemplateKind =
  | 'PRICE_LIST'
  | 'PRODUCT_CATALOG'
  | 'FLYER'
  | 'RECEIPT'
  | 'QUOTATION'
  | 'BROCHURE'
  | 'PROMO';

export type PdfGenerateInput = {
  template: PdfTemplateKind;
  title: string;
  productIds?: string[];
  brand: BrandBrain;
  promoText?: string;
  currency?: string;
};

type ProductRow = {
  name: string;
  sku: string;
  salePrice: string;
  imageUrl: string | null;
};

async function loadProducts(productIds?: string[]): Promise<ProductRow[]> {
  if (productIds?.length) {
    const rows = await db
      .select()
      .from(products)
      .where(and(eq(products.isActive, true), inArray(products.id, productIds)));
    return rows.map(mapProduct);
  }
  const rows = await db.select().from(products).where(eq(products.isActive, true)).limit(100);
  return rows.map(mapProduct);
}

function mapProduct(p: typeof products.$inferSelect): ProductRow {
  return {
    name: p.name,
    sku: p.sku,
    salePrice: String(p.salePrice),
    imageUrl: p.imageUrl,
  };
}

async function readMerchantName(): Promise<string> {
  const [bp] = await db.select().from(businessProfile).limit(1);
  return bp?.name || process.env.NEXT_PUBLIC_STORE_NAME || 'Grabber Store';
}

function hexToRgb(hex: string) {
  const h = hex.replace('#', '');
  const n = parseInt(h.length === 3 ? h.split('').map((c) => c + c).join('') : h, 16);
  return rgb(((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255);
}

export async function generatePdfDocument(input: PdfGenerateInput): Promise<Uint8Array> {
  const merchant = await readMerchantName();
  const currency = input.currency || 'LKR';
  const catalog = await loadProducts(input.productIds);
  const brandColor = hexToRgb(input.brand.primaryColor || '#047857');

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const page = pdf.addPage([595, 842]); // A4
  const { width, height } = page.getSize();
  let y = height - 48;

  page.drawText(merchant, { x: 48, y, size: 18, font: fontBold, color: brandColor });
  y -= 22;
  page.drawText(input.brand.tagline, { x: 48, y, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
  y -= 28;

  const templateLabel = input.template.replace(/_/g, ' ');
  page.drawText(`${templateLabel} — ${input.title}`, { x: 48, y, size: 14, font: fontBold });
  y -= 20;

  if (input.promoText) {
    page.drawText(input.promoText, { x: 48, y, size: 11, font, color: brandColor, maxWidth: width - 96 });
    y -= 24;
  }

  page.drawLine({ start: { x: 48, y }, end: { x: width - 48, y }, thickness: 1, color: rgb(0.85, 0.85, 0.85) });
  y -= 20;

  if (input.template === 'FLYER' || input.template === 'PROMO' || input.template === 'BROCHURE') {
    page.drawText('Featured offer', { x: 48, y, size: 12, font: fontBold });
    y -= 18;
    page.drawText(
      input.promoText || `Shop ${merchant} — ${input.brand.whatsappCta}. Islandwide delivery.`,
      { x: 48, y, size: 11, font, maxWidth: width - 96 },
    );
    y -= 36;
  }

  page.drawText('Product', { x: 48, y, size: 10, font: fontBold });
  page.drawText('SKU', { x: 280, y, size: 10, font: fontBold });
  page.drawText(`Price (${currency})`, { x: 400, y, size: 10, font: fontBold });
  y -= 16;

  for (const p of catalog.slice(0, 28)) {
    if (y < 72) break;
    page.drawText(p.name.slice(0, 42), { x: 48, y, size: 9, font, maxWidth: 220 });
    page.drawText(p.sku.slice(0, 16), { x: 280, y, size: 9, font });
    page.drawText(Number(p.salePrice).toLocaleString('en-LK'), { x: 400, y, size: 9, font });
    y -= 14;
  }

  if (!catalog.length) {
    page.drawText('No products in catalog — add products in Inventory first.', {
      x: 48,
      y,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
  }

  page.drawText(`${input.brand.whatsappCta} · Generated by Grabber Creative Engine`, {
    x: 48,
    y: 36,
    size: 8,
    font,
    color: rgb(0.55, 0.55, 0.55),
  });

  return pdf.save();
}

export const PDF_TEMPLATES: { id: PdfTemplateKind; label: string; description: string }[] = [
  { id: 'PRICE_LIST', label: 'Price list', description: 'Live sale prices from inventory' },
  { id: 'PRODUCT_CATALOG', label: 'Product catalog', description: 'SKU + price table for sharing' },
  { id: 'FLYER', label: 'Flyer', description: 'Promotional one-pager with CTA' },
  { id: 'QUOTATION', label: 'Quotation', description: 'Branded quote layout from products' },
  { id: 'RECEIPT', label: 'Receipt', description: 'Simple receipt-style PDF' },
  { id: 'BROCHURE', label: 'Brochure', description: 'Multi-section product brochure' },
  { id: 'PROMO', label: 'Promotional PDF', description: 'Offer / discount announcement' },
];
